"""The SDL mapping database the box serves to every emulator.

`process_manager` exports SDL_GAMECONTROLLERCONFIG_FILE to every game it
launches, and SDL merges that file into its built-in table at init. Until now
the file was the vendored community database and nothing else, so a pad the
community never described was a pad no emulator could bind — the one hole the
mapping wizard exists to close.

So there are now two files, and the distinction matters:

    gamecontrollerdb.txt        vendored, SHIPPED, replaced by every OTA.
                                Community work, 2200 lines, not ours to edit.
    gamecontrollerdb_user.txt   the owner's own captures. Never shipped, never
                                touched by an update.

What SDL reads is neither: it is `served()`, a concatenation regenerated
whenever the user file changes. Keeping the owner's lines in their own file is
what makes them survive an OTA — the vendored one is overwritten wholesale by
`update/linux.sh`, and a captured mapping written into it would be lost on the
next release. Both live under DATA_DIR, outside the install tree, for the same
reason and one more: in production GameCore is /opt/GameCore, and the backend
does not own it.

## The order is measured, not assumed

SDL parses a mapping file top to bottom, and it does NOT stop at the first
entry for a GUID. Which of two lines for one GUID survives decides whether the
owner's capture beats the community's guess or loses to it, silently — the pad
would simply keep behaving the way it did before the wizard ran, with a user
file on disk that looks applied.

Measured on this box against four independent SDL builds, each given a file
naming one GUID twice:

    Ryujinx's bundled libSDL2.so   (real SDL 2.x)      LAST line wins
    PCSX2's libSDL3.so.0.2.26                          LAST line wins
    RPCS3's libSDL3.so.0.4.10                          LAST line wins
    the host's libSDL3.so.0.4.12                       LAST line wins

Unanimous, so "the user's mapping takes priority" means the user's lines are
written **at the END** of the served file, after the community ones. Reading
that as "user first" and putting them at the top is the exact inversion this
paragraph exists to prevent: it produces a file that contains the capture and
an emulator that ignores it.

`test_mapping_db.py` re-runs that probe against every SDL it can find, so the
day an SDL release changes its mind the suite says so instead of the pad.

## Winning is not always the right outcome

That same property is why a captured line is not automatically served. Last
wins means a capture REPLACES SDL's built-in mapping for its GUID rather than
supplementing it — in every emulator the box launches at once, since
`process_manager` exports this file to all of them.

A capture is measured through /dev/input, so it is the pad's real numbering
only for a pad SDL reads the same way. For the Sony, Microsoft and Nintendo
families SDL uses a HIDAPI driver whose button order is different, and it says
so in the GUID's byte 14. Measured on the reference box after the wizard first
ran, one DualShock 4:

    SDL on its own          x:b2  y:b3  back:b4  start:b6  leftshoulder:b9
    SDL given this file     x:b3  y:b2  back:b8  start:b9  leftshoulder:b4

`servable()` is the rule that follows: what the owner captured is stored for
ever and served only where it is true. Stored and served are different states,
and `/controllers/mapping/saved` reports both, because a capture that is doing
nothing must not look like one that is working.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

from . import controllers
from .controllers import DB_FILE
from .helpers.base import atomic_write

log = logging.getLogger(__name__)

# Outside the install tree on purpose — see the module docstring. Sibling of
# the controller snapshots, which are the same kind of thing: box state the
# owner produced, which no release may overwrite.
HOME = Path.home()
DATA_DIR = HOME / ".local/share/gamecore"

# The owner's captures. This is the file the wizard writes.
USER_DB = DATA_DIR / "gamecontrollerdb_user.txt"

# The concatenation handed to SDL. Derived — deleting it costs nothing, it is
# rebuilt from the two sources.
SERVED_DB = DATA_DIR / "gamecontrollerdb.txt"

_HEADER = (
    "# Generated by GameCore — do not edit.\n"
    "# Community database first, then the owner's captures: SDL keeps the LAST\n"
    "# line it reads for a GUID, so what is appended here wins. Edit\n"
    "# gamecontrollerdb_user.txt instead; this file is rebuilt from it.\n"
)

# What the two sources looked like when this file was built. Compared on every
# `served()` to decide whether it is still current.
#
# **A timestamp alone is not enough, and an OTA is exactly why.**
# `update/linux.sh` installs the new release with `rsync -a`, and `-a` implies
# `-t`: the vendored database arrives carrying the mtime it had in the archive,
# which can be OLDER than the merge already sitting in the data directory. A
# "newer than me?" test therefore answers no to a database that has genuinely
# just changed, and the box keeps serving the previous release's merge for ever
# — silently, because the file is present and looks right.
#
# Size and mtime together, recorded rather than inferred: two databases that
# differ in content and match on both is not a case worth designing for, and
# any mismatch in either direction — newer, older, resized — is a rebuild.
_SOURCES_RE = re.compile(r"^# sources: (\S+) (\S+)$", re.M)


def _fingerprint(path: Path) -> str:
    try:
        st = path.stat()
        return f"{st.st_size}:{st.st_mtime_ns}"
    except OSError:
        return "-"

_USER_BANNER = "\n# ── captured on this box (mapping wizard) ──\n"

# A mapping line is `<32 hex GUID>,<name>,<binding>,<binding>,…`. Anything else
# — a comment, a blank, a truncated write — is not one, and must not be counted
# as one: a half-written line silently shadowing a good entry is the failure
# this parser exists to make impossible.
_LINE_RE = re.compile(r"^([0-9a-fA-F]{32}),([^,]*),(.*)$")


def parse(line: str) -> tuple[str, str, str] | None:
    """(guid, name, bindings) for a real mapping line, else None."""
    m = _LINE_RE.match(line.strip())
    if not m:
        return None
    guid, name, bindings = m.group(1).lower(), m.group(2).strip(), m.group(3)
    if not name or not bindings:
        return None
    return guid, name, bindings


def platform_of(line: str) -> str:
    """The `platform:` field, or "". SDL keys its table on GUID **and**
    platform, so a Windows line and a Linux line for one GUID do not collide
    and replacing one with the other would drop a mapping rather than update
    it."""
    parsed = parse(line)
    if not parsed:
        return ""
    for token in parsed[2].split(","):
        key, _, value = token.partition(":")
        if key.strip() == "platform":
            return value.strip()
    return ""


def read_user() -> list[str]:
    """The owner's mapping lines, comments and blanks dropped."""
    try:
        text = USER_DB.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    return [ln.strip() for ln in text.splitlines() if parse(ln)]


def servable(lines: list[str]) -> list[str]:
    """The captured lines it is safe to hand SDL, out of everything stored.

    **A capture is measured through /dev/input, and it is only true of a pad
    SDL reads the same way.** The wizard files one line per SDL identity the
    pad has, and for a Sony, Microsoft or Nintendo controller those identities
    belong to a HIDAPI driver whose button order is a different one. SDL keeps
    the LAST line it reads for a GUID — the property this file is built around
    — so such a line does not sit harmlessly beside SDL's built-in mapping, it
    REPLACES it, for every emulator the box launches.

    Measured on the reference box, one DualShock 4, after the wizard ran:

        SDL's own mapping   x:b2  y:b3  back:b4  start:b6  leftshoulder:b9
        what the served     x:b3  y:b2  back:b8  start:b9  leftshoulder:b4
        file made it say

    The second is the capture, and every emulator that asks SDL what this pad
    is — RPCS3, Dolphin, Ryujinx, PCSX2, DuckStation — was being told it. Those
    five were last verified in game BEFORE the wizard first ran, so the cost of
    this was never observed; it is measured here rather than reported.

    The line stays in `USER_DB` untouched. That file is the owner's work and
    nothing here deletes it — `remove()` is how a capture goes away, on
    purpose. This decides only what is SERVED, which is a derived file.
    """
    keep, dropped = [], []
    for line in lines:
        parsed = parse(line)
        guid = parsed[0] if parsed else ""
        (keep if controllers.guid_read_through_evdev(guid) else dropped).append(line)
    for line in dropped:
        log.info("mapping_db: not serving the capture for %s — SDL reads that "
                 "pad through a driver whose button order is not the one the "
                 "wizard measured, and SDL already ships a mapping for it",
                 (parse(line) or ("?",))[0])
    return keep


def upsert(line: str) -> str:
    """Add or replace one captured mapping, then rebuild what SDL reads.

    Keyed by (guid, platform) rather than GUID alone, so re-running the wizard
    on the same pad REPLACES its line instead of stacking a second one. Both
    would resolve to the newer entry today — last wins — but a file that grows
    a line per attempt is a file whose next reader cannot tell which mapping is
    live, and `remove()` would only ever unbury the previous one.
    """
    parsed = parse(line)
    if not parsed:
        raise ValueError(f"not an SDL mapping line: {line[:60]!r}")
    guid, _name, _bindings = parsed
    platform = platform_of(line)

    kept = [ln for ln in read_user()
            if not (parse(ln)[0] == guid and platform_of(ln) == platform)]
    kept.append(line.strip())
    _write_user(kept)
    rebuild()
    log.info("mapping_db: saved a mapping for %s (%s)", guid, platform or "any")
    return line.strip()


def remove(guid: str) -> bool:
    """Drop every user line for a GUID. True when something went away.

    The inverse of the wizard, and it exists for the same reason `forget()`
    does next door: a capture that turns out wrong must be undoable from the
    couch, not only from a shell.
    """
    guid = guid.lower()
    before = read_user()
    kept = [ln for ln in before if parse(ln)[0] != guid]
    if len(kept) == len(before):
        return False
    _write_user(kept)
    rebuild()
    log.info("mapping_db: dropped the saved mapping for %s", guid)
    return True


def _write_user(lines: list[str]) -> None:
    USER_DB.parent.mkdir(parents=True, exist_ok=True)
    body = "".join(f"{ln}\n" for ln in lines)
    atomic_write(USER_DB, "# GameCore — controller mappings captured on this "
                          "box. Survives updates.\n" + body)


def rebuild() -> Path | None:
    """Regenerate the served file: community lines, then the owner's servable ones.

    Returns the path written, or None when there is nothing to serve — no user
    mapping and no vendored database, which is a box with nothing to say and
    must NOT leave an empty file behind for SDL to read as an answer.

    "Servable" and not "stored": see `servable()`. A capture whose GUID names a
    pad SDL reads through another driver would not be added to SDL's knowledge
    here, it would REPLACE it — the last-line-wins property this file is built
    on, working against the box.
    """
    user = servable(read_user())
    try:
        community = DB_FILE.read_text(encoding="utf-8", errors="replace")
    except OSError:
        community = ""
        if not user:
            return None
    if not community and not user:
        return None
    parts = [_HEADER,
             f"# sources: {_fingerprint(DB_FILE)} {_fingerprint(USER_DB)}\n",
             community]
    if not community.endswith("\n"):
        parts.append("\n")
    if user:
        parts.append(_USER_BANNER)
        parts.extend(f"{ln}\n" for ln in user)
    SERVED_DB.parent.mkdir(parents=True, exist_ok=True)
    atomic_write(SERVED_DB, "".join(parts))
    return SERVED_DB


def served() -> Path | None:
    """The file SDL_GAMECONTROLLERCONFIG_FILE must name, or None.

    Rebuilt whenever either source no longer matches the fingerprint recorded
    in its header — see `_SOURCES_RE` for why that is a fingerprint and not a
    "newer than me" test. So a box that has never run the wizard still gets the
    vendored database, one that has does not depend on the wizard having been
    the last thing to run, and an OTA that replaces the community file
    underneath us is noticed even though rsync hands it an older timestamp.
    """
    want = f"# sources: {_fingerprint(DB_FILE)} {_fingerprint(USER_DB)}"
    try:
        if not SERVED_DB.is_file():
            stale = True
        else:
            # The header only: this file is 600 KB and the question is four
            # lines in.
            with SERVED_DB.open(encoding="utf-8", errors="replace") as f:
                head = "".join(next(f, "") for _ in range(8))
            stale = want not in head
    except OSError:
        stale = True
    if stale:
        try:
            rebuild()
        except OSError:
            # Never fatal: an unwritable data directory must cost the captured
            # mappings, not the ability to launch a game at all.
            log.warning("mapping_db: could not rebuild %s", SERVED_DB,
                        exc_info=True)
    if SERVED_DB.is_file():
        return SERVED_DB
    return DB_FILE if DB_FILE.is_file() else None
