Audio:
  Audio Channel Layout: Automatic
  Audio Device: "@@@default@@@"
  Audio Format: Stereo
  Audio Formats: 0
  Audio Provider: CellAudio
  Convert to 16 bit: false
  Desired Audio Buffer Duration: 100
  Disable Sampling Skip: false
  Dump to file: false
  Enable Buffering: true
  Enable Time Stretching: false
  Master Volume: 100
  Microphone Devices: "@@@@@@@@@@@@"
  Microphone Type: "Null"
  Music Handler: Qt
  RSXAudio Avport: HDMI 0
  Renderer: Cubeb
  Time Stretching Threshold: 75
Core:
  Accurate Cache Line Stores: false
  Accurate PPU 128-byte Reservation Op Max Length: 0
  Accurate RSX reservation access: true
  Accurate SPU DMA: false
  Accurate SPU Reservations: true
  Allow RSX CPU Preemptions: true
  Assume External Debugger: false
  Clocks scale: 100
  Debug Console Mode: false
  Disable SPU GETLLAR Spin Optimization: false
  Enable Performance Report: false
  Enable TSX: Disabled
  HLE lwmutex: false
  Hook static functions: false
  LLVM Precompilation: true
  Libraries Control:
    []
  MFC Commands Shuffling In Steps: false
  MFC Commands Shuffling Limit: 0
  MFC Commands Timeout: 0
  MFC Debug: false
  Max CPU Preempt Count: 0
  Max LLVM Compile Threads: 0
  Max SPURS Threads: 6
  PPU Accurate Non-Java Mode: false
  PPU Accurate Vector NaN Values: false
  PPU Calling History: false
  PPU Debug: false
  PPU Decoder: Recompiler (LLVM)
  PPU Fixup Vector NaN Values: false
  PPU LLVM Greedy Mode: false
  PPU LLVM Java Mode Handling: true
  PPU Profiler: false
  PPU Set FPCC Bits: false
  PPU Set Saturation Bit: false
  PPU Threads: 2
  PPU Vector NaN Handling: true
  Performance Report Threshold: 500
  Precise SPU Verification: false
  Preferred SPU Threads: 0
  RSX FIFO Accuracy: Atomic
  RSX FIFO Fetch Accuracy: Atomic
  SPU Block Size: Safe
  SPU Cache: true
  SPU Debug: false
  SPU Decoder: Recompiler (LLVM)
  SPU GETLLAR Busy Waiting Percentage: 100
  SPU LLVM Lower Bound: 0
  SPU LLVM Upper Bound: 18446744073709551615
  SPU Profiler: false
  SPU Reservation Busy Waiting Enabled: false
  SPU Reservation Busy Waiting Percentage 1: 100
  SPU Verification: true
  SPU Wake-Up Delay: 0
  SPU Wake-Up Delay Thread Mask: 63
  SPU XFloat Accuracy: Approximate
  SPU delay penalty: 3
  SPU loop detection: false
  Save LLVM logs: false
  Set DAZ and FTZ: false
  Sleep Timers Accuracy: As Host
  Stub PPU Traps: 0
  TSX Transaction First Limit: 800
  TSX Transaction Second Limit: 2000
  Thread Scheduler Mode: Operating System
  Use Accurate DFMA: true
  Use LLVM CPU: ""
  Usleep Time Addend: 0
  XFloat Accuracy: Approximate
Input/Output:
  Allow move hue set by game: false
  Background input enabled: true
  Buzz emulated controller: "Null"
  Camera: "Null"
  Camera ID: Default
  Camera flip: None
  Camera type: Unknown
  Emulated Midi devices: Keyboardßßß@@@Keyboardßßß@@@Keyboardßßß@@@
  Fake Move Rotation Cone: 10
  Fake Move Rotation Cone (Vertical): 10
  GHLtar emulated controller: "Null"
  IO Debug overlay: false
  Keep pads connected: false
  Keyboard: "Null"
  Load SDL GameController Mappings: true
  Lock overlay input to player one: false
  Mouse: Basic
  Mouse Debug overlay: false
  Move: "Null"
  Pad handler mode: Single-threaded
  Pad handler sleep (microseconds): 1000
  Paint move spheres: false
  SDL Camera ID: Default
  Show move cursor: false
  Turntable emulated controller: "Null"
Log:
  {}
Miscellaneous:
  Automatically start games after boot: true
  Enable GameMode: false
  Exit RPCS3 when process finishes: false
  GDB Server: 127.0.0.1:2345
  Pause Emulation During Home Menu: false
  Pause emulation on RPCS3 focus loss: false
  Play music during boot sequence: true
  Prevent display sleep while running games: true
  Show PPU compilation hint: true
  Show RPCN popups: true
  Show analog limiter toggle hint: true
  Show autosave/autoload hint: false
  Show capture hints: true
  Show fatal error hints: false
  Show mouse and keyboard toggle hint: true
  Show pressure intensity toggle hint: true
  Show shader compilation hint: true
  Show trophy popups: true
  Silence All Logs: false
  Start games in fullscreen mode: false
  Use native user interface: true
  Use recursive scan: false
  Window Title Format: "FPS: %F | %R | %V | %T [%t]"
Net:
  Bind address: 0.0.0.0
  Clans Enabled: false
  DNS address: 8.8.8.8
  Derive MAC from PSID: false
  IP address: 0.0.0.0
  IP swap list: ""
  Internet enabled: Disconnected
  PSN Country: us
  PSN status: Disconnected
  UPNP Enabled: false
Savestate:
  Compatible Savestate Mode: false
  Inspection Mode Savestates: false
  Maximum SaveState Files: 4
  Maximum SaveState Files Space (MiB): 4096
  Save Disc Game Data: false
  Start Paused: false
  Suspend Emulation Savestate Mode: false
System:
  Console PSID: 0x240135C14C715743D7C95499F6AC3589
  Console time offset (s): 0
  Date Format: ddmmyyyy
  Enter button assignment: Enter with cross
  HDD Model Name: ""
  HDD Serial Number: ""
  Keyboard Type: English keyboard (US standard)
  Language: English (US)
  License Area: SCEA
  Process ARGV:
    {}
  System Name: RPCS3-557
  Time Format: clock24
VFS:
  Disk cache maximum size (MB): 5120
  Empty /dev_hdd0/tmp/: true
  Enable /host_root/: false
  Initialize Directories: true
  Limit disk cache size: false
Video:
  3D Display Enabled: false
  3D Display Mode: Disabled
  Accurate ZCULL stats: false
  Allow Host GPU Labels: false
  Anisotropic Filter Override: 16
  Aspect ratio: 16:9
  Consecutive Frames To Draw: 1
  Consecutive Frames To Skip: 1
  Custom Anaglyph Matrices:
    Matrix Left:
      {}
    Matrix Right:
      {}
  DECR memory layout: false
  Debug Program Analyser: false
  Debug output: false
  Debug overlay: false
  Disable Asynchronous Memory Manager: false
  Disable FIFO Reordering: false
  Disable Hardware ColorSpace Remapping: false
  Disable MSL Fast Math: false
  Disable On-Disk Shader Cache: false
  Disable Vertex Cache: false
  Disable Video Output: false
  Disable Vulkan Memory Allocator: false
  Disable ZCull Occlusion Queries: false
  Driver Recovery Timeout: 1000000
  Driver Wake-Up Delay: 300
  Emulate Special Depth Comparison: false
  Enable Frame Skip: false
  FidelityFX CAS Sharpening Intensity: 50
  Force CPU Blit: false
  Force Hardware MSAA Resolve: false
  Force High Precision Z buffer: false
  Frame limit: 30
  Framebuffer Aliasing Heuristic Bias: Auto
  Handle RSX Memory Tiling: false
  Log shader programs: false
  MSAA: Disabled
  Minimum Scalable Dimension: 16
  Multithreaded RSX: true
  Output Scaling Mode: FidelityFX Super Resolution
  Performance Overlay:
    Body Background (hex): "#002339FF"
    Body Color (hex): "#FFE138FF"
    Center Horizontally: false
    Center Vertically: false
    Detail level: Medium
    Enable Framerate Graph: false
    Enable Frametime Graph: false
    Enabled: false
    Font: n023055ms.ttf
    Font size (px): 10
    Framerate datapoints: 50
    Framerate graph detail level: All
    Frametime datapoints: 170
    Frametime graph detail level: All
    Horizontal Margin (%): 4
    Horizontal Margin (px): 50
    Metrics update interval (ms): 350
    Opacity (%): 70
    Position: Top Left
    Title Background (hex): "#00000000"
    Title Color (hex): "#F26C24FF"
    Use Window Space: false
    Vertical Margin (%): 7
    Vertical Margin (px): 50
  Read Color Buffers: true
  Read Depth Buffer: true
  Record With Overlays: true
  Relaxed ZCULL Sync: true
  Renderdoc Compatibility Mode: false
  Renderer: Vulkan
  Resolution: 1280x720
  Resolution Scale: 100
  Screen size in inches: 24
  Second Frame Limit: 0
  Shader Compiler Threads: 0
  Shader Loading Dialog:
    Allow custom background: true
    Blur effect strength: 0
    Darkening effect strength: 30
  Shader Mode: Async Recompiler (multi-threaded)
  Shader Precision: Low
  Stretch To Display Area: false
  Strict Rendering Mode: false
  Strict Texture Flushing: false
  Texture LOD Bias Addend: 0
  Use GPU texture scaling: false
  Use full RGB output range: true
  VSync: true
  VSync Mode: Disabled
  Vblank NTSC Fixup: false
  Vblank Rate: 60
  Vulkan:
    Adapter: AMD Radeon Graphics (RADV REMBRANDT)
    Asynchronous Queue Scheduler: Safe
    Asynchronous Texture Streaming: true
    Asynchronous Texture Streaming 2: true
    Exclusive Fullscreen Mode: Automatic
    FidelityFX CAS Sharpening Intensity: 50
    Force FIFO present mode: false
    Force primitive restart flag: false
    Use Re-BAR for GPU uploads: true
    VRAM allocation limit (MB): 65536
  Write Color Buffers: true
  Write Depth Buffer: true