"""GENERATED by scripts/gen-catalog.py — do not edit.

Source: catalog/<id>/pack.json. The installer binary is built before the
repository is on the machine, so this list is baked in rather than read.
"""

EMULATORS = [
    ('azahar', 'Azahar', 'Nintendo 3DS'),
    ('cemu', 'Cemu', 'Wii U'),
    ('dolphin', 'Dolphin', 'GameCube / Wii'),
    ('ryujinx', 'Ryujinx', 'Nintendo Switch'),
    ('duckstation', 'DuckStation', 'PlayStation'),
    ('pcsx2', 'PCSX2', 'PlayStation 2'),
    ('rpcs3', 'RPCS3', 'PlayStation 3'),
    ('ppsspp', 'PPSSPP', 'PlayStation Portable'),
    ('gopher64', "Rosalie's Mupen GUI", 'Nintendo 64'),
    ('melonds', 'melonDS', 'Nintendo DS'),
    ('mgba', 'mGBA', 'Game Boy Advance'),
    ('xenia', 'Xenia Canary', 'Xbox 360'),
    ('shadps4', 'shadPS4', 'PlayStation 4'),
]

APPS = [
    ('steam', 'Steam', 'PC games (Flatpak, Big Picture)'),
    ('youtube', 'YouTube', 'TV app in a Firefox kiosk'),
    ('twitch', 'Twitch (EmberTV)', 'Twitch for the big screen'),
    ('stremio', 'Stremio', 'Media center (gamepad-friendly)'),
]
