"""GENERATED by scripts/gen-catalog.py — do not edit.

Source: catalog/<id>/pack.json. The installer binary is built before the
repository is on the machine, so this list is baked in rather than read.
"""

EMULATORS = [
    ('azahar', 'Azahar', 'Nintendo 3DS'),
    ('cemu', 'Cemu', 'Wii U'),
    ('dolphin', 'Dolphin', 'GameCube / Wii'),
    ('ryujinx', 'Ryujinx', 'Nintendo Switch'),
    ('duckstation', 'DuckStation', 'PlayStation'),
    ('pcsx2', 'PCSX2', 'PlayStation 2'),
    ('rpcs3', 'RPCS3', 'RPCS3 Smart Pack: upstream launch behavior plus official config/patch database synchronization.'),
    ('ppsspp', 'PPSSPP', 'PlayStation Portable'),
    ('gopher64', "Rosalie's Mupen GUI", 'Nintendo 64'),
    ('melonds', 'melonDS', 'Nintendo DS'),
    ('mgba', 'mGBA', 'Game Boy Advance'),
    ('xenia', 'Xenia Canary', 'Xbox 360'),
    ('shadps4', 'shadPS4', 'PlayStation 4'),
    ('snes9x', 'Snes9x', 'Super Nintendo'),
    ('nes', 'RetroArch / mesen', 'Nintendo Entertainment System'),
    ('fds', 'RetroArch / mesen', 'Family Computer Disk System'),
    ('mastersystem', 'RetroArch / genesis-plus-gx', 'Sega Master System'),
    ('gamegear', 'RetroArch / genesis-plus-gx', 'Sega Game Gear'),
    ('sg1000', 'RetroArch / genesis-plus-gx', 'Sega SG-1000'),
    ('megadrive', 'RetroArch / genesis-plus-gx', 'Sega Mega Drive / Genesis'),
    ('megacd', 'RetroArch / genesis-plus-gx', 'Sega Mega-CD / Sega CD'),
    ('sega32x', 'RetroArch / picodrive', 'Sega Mega Drive 32X'),
    ('saturn', 'RetroArch / kronos', 'Sega Saturn'),
    ('dreamcast', 'RetroArch / flycast', 'Sega Dreamcast'),
    ('naomi', 'RetroArch / flycast', 'Sega Naomi'),
    ('naomigd', 'RetroArch / flycast', 'Sega Naomi GD-ROM'),
    ('atomiswave', 'RetroArch / flycast', 'Sammy Atomiswave'),
    ('pcengine', 'RetroArch / beetle-pce', 'NEC PC Engine / TurboGrafx-16'),
    ('pcenginecd', 'RetroArch / beetle-pce', 'NEC PC Engine CD / TurboGrafx-CD'),
    ('supergrafx', 'RetroArch / beetle-pce', 'NEC PC Engine SuperGrafx'),
    ('mame', 'RetroArch / mame', 'Arcade (MAME)'),
]

APPS = [
    ('steam', 'Steam', 'PC games (Flatpak, Big Picture)'),
    ('youtube', 'YouTube', 'TV app in a Firefox kiosk'),
    ('twitch', 'Twitch (EmberTV)', 'Twitch for the big screen'),
    ('stremio', 'Stremio', 'Media center (gamepad-friendly)'),
]
