/**
 * The pure helpers a view needs to draw the box's data, gathered for `sdk.format`.
 *
 * Every one of these was already in the tree and reachable only by the default
 * views. Writing the default UI back as an ordinary theme is what surfaced
 * them: a dashboard cannot colour a system, a library cannot turn
 * `Super_Mario_64_(USA).z64` into a title, and neither can say "3h 42m" the way
 * the rest of the UI says it.
 *
 * A theme that reimplements these does not fail — it drifts, which is worse.
 * `formatGameName` alone carries enough accumulated ROM-naming rules to have
 * its own test file; a second copy in a theme would get the same input subtly
 * wrong and nobody would know which one was right.
 *
 * Re-exports rather than definitions, except `systemColor`: the point is one
 * implementation, reachable from two places.
 */
import { SYSTEM_COLORS } from './systemColors'
import { formatGameName } from './formatGameName'
import { hexToRgb, fmtTime, fmtDate } from '../components/ui'
import type { SystemEntry } from '../api'

/**
 * A system's accent colour.
 *
 * The pack's own colour first, then the generated table, then the house purple.
 * The fallback chain matters: `SystemEntry.color` is optional and absent for
 * anything the catalogue does not describe, so a theme reading `system.color`
 * alone paints half a dashboard purple and looks broken rather than plain.
 *
 * Lives here and not in systemColors.ts because that file is generated by
 * scripts/gen-catalog.py, which rewrites it whole — a resolver added there
 * survives exactly until the next person runs the generator.
 */
export function systemColor(system: Pick<SystemEntry, 'id' | 'color'>): string {
  return system.color || SYSTEM_COLORS[String(system.id).toLowerCase()] || '#7c3aed'
}

export { formatGameName, hexToRgb, fmtTime, fmtDate, SYSTEM_COLORS }
